# Generated by Django 5.2.1 on 2025-05-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_used', models.PositiveIntegerField()),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumables.consumable')),
            ],
        ),
    ]
